/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, visit the plugin's repository (main.ts).
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_CODE: () => VIEW_TYPE_CODE,
  default: () => CodeFileViewerPlugin,
  parseMappings: () => parseMappings
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_CODE = "code-file-view";
var MAX_HIGHLIGHT_CHARS = 1e6;
var RESERVED_EXTENSIONS = /* @__PURE__ */ new Set([
  "md",
  "canvas",
  "pdf",
  "png",
  "jpg",
  "jpeg",
  "gif",
  "bmp",
  "svg",
  "webp",
  "avif",
  "mp3",
  "wav",
  "m4a",
  "ogg",
  "3gp",
  "flac",
  "mp4",
  "webm",
  "ogv",
  "mov",
  "mkv"
]);
var DEFAULT_EXTENSION_MAP = {
  // Python
  py: "python",
  pyw: "python",
  // JavaScript / TypeScript
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "jsx",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  // Shell & friends
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  env: "bash",
  ps1: "powershell",
  psm1: "powershell",
  bat: "batch",
  cmd: "batch",
  // Data / config
  sql: "sql",
  yml: "yaml",
  yaml: "yaml",
  toml: "toml",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  properties: "properties",
  json: "json",
  jsonc: "json",
  json5: "json",
  // Markup & styles
  xml: "markup",
  html: "markup",
  htm: "markup",
  vue: "markup",
  svelte: "markup",
  css: "css",
  scss: "scss",
  less: "less",
  // Compiled languages
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  swift: "swift",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hh: "cpp",
  cs: "csharp",
  // Scripting & others
  rb: "ruby",
  php: "php",
  pl: "perl",
  pm: "perl",
  lua: "lua",
  r: "r",
  jl: "julia",
  dart: "dart",
  hs: "haskell",
  ex: "elixir",
  exs: "elixir",
  dockerfile: "docker",
  tf: "hcl",
  graphql: "graphql",
  gql: "graphql",
  diff: "diff",
  patch: "diff",
  tex: "latex",
  // Plain text
  log: "plain",
  txt: "plain",
  text: "plain",
  csv: "plain",
  tsv: "plain"
};
var DEFAULT_SETTINGS = {
  extensionMap: { ...DEFAULT_EXTENSION_MAP },
  lineNumbers: true
};
var CodeFileViewerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.prismPromise = null;
    this.registeredExtensions = [];
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_CODE, (leaf) => new CodeFileView(leaf, this));
    this.applyExtensions();
    this.addSettingTab(new CodeFileViewerSettingTab(this.app, this));
  }
  /** Lazily fetch Obsidian's bundled Prism instance (shared with reading view). */
  getPrism() {
    if (!this.prismPromise) {
      this.prismPromise = (0, import_obsidian.loadPrism)();
    }
    return this.prismPromise;
  }
  /**
   * (Re-)register the file extensions from settings onto our view.
   * Registration failures (e.g. another plugin owns the extension) are
   * logged and skipped so one conflict never breaks the rest.
   */
  applyExtensions() {
    var _a;
    if (this.registeredExtensions.length > 0) {
      const vr = this.app.viewRegistry;
      try {
        (_a = vr == null ? void 0 : vr.unregisterExtensions) == null ? void 0 : _a.call(vr, this.registeredExtensions);
      } catch (e) {
        console.warn("Code File Viewer: could not unregister old extensions", e);
      }
      this.registeredExtensions = [];
    }
    for (const rawExt of Object.keys(this.settings.extensionMap)) {
      const ext = rawExt.toLowerCase().replace(/^\./, "");
      if (!ext || RESERVED_EXTENSIONS.has(ext)) continue;
      try {
        this.registerExtensions([ext], VIEW_TYPE_CODE);
        this.registeredExtensions.push(ext);
      } catch (e) {
        console.warn(
          `Code File Viewer: could not register ".${ext}" \u2014 probably claimed by Obsidian or another plugin.`,
          e
        );
      }
    }
  }
  /** Re-render any open code views (after a settings change). */
  rerenderOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_CODE)) {
      const view = leaf.view;
      if (view instanceof CodeFileView) void view.render();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CodeFileView = class extends import_obsidian.TextFileView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Guards against out-of-order async renders when switching files fast. */
    this.renderSeq = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CODE;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "Code file";
  }
  getIcon() {
    return "file-code";
  }
  /* TextFileView contract — we are read-only, so data never changes. */
  getViewData() {
    return this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    void this.render();
  }
  clear() {
    this.data = "";
    this.contentEl.empty();
  }
  async render() {
    var _a, _b, _c, _d, _e, _f, _g;
    const seq = ++this.renderSeq;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("cfv-view-content");
    const ext = (_c = (_b = (_a = this.file) == null ? void 0 : _a.extension) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
    const langId = (_d = this.plugin.settings.extensionMap[ext]) != null ? _d : "plain";
    const toolbar = contentEl.createDiv({ cls: "cfv-toolbar" });
    const info = toolbar.createDiv({ cls: "cfv-toolbar-info" });
    info.createSpan({
      cls: "cfv-lang",
      text: ext ? `.${ext} \xB7 ${langId}` : langId
    });
    const note = info.createSpan({ cls: "cfv-note" });
    const copyBtn = toolbar.createEl("button", {
      cls: "cfv-copy",
      text: "Copy"
    });
    copyBtn.setAttr("aria-label", "Copy file contents");
    copyBtn.addEventListener("click", () => {
      void navigator.clipboard.writeText(this.data).then(() => {
        new import_obsidian.Notice("File contents copied");
      });
    });
    const scroller = contentEl.createDiv({ cls: "cfv-scroller" });
    const wrap = scroller.createDiv({ cls: "cfv-codewrap" });
    if (this.plugin.settings.lineNumbers) {
      let count = this.data.split("\n").length;
      if (this.data.endsWith("\n")) count -= 1;
      count = Math.max(count, 1);
      const gutterText = Array.from(
        { length: count },
        (_, i) => String(i + 1)
      ).join("\n");
      const gutter = wrap.createEl("pre", {
        cls: "cfv-gutter",
        text: gutterText
      });
      gutter.setAttr("aria-hidden", "true");
    }
    const pre = wrap.createEl("pre", { cls: "cfv-pre" });
    const code = pre.createEl("code", { cls: `language-${langId}` });
    let prism = null;
    let grammar;
    const tooLarge = this.data.length > MAX_HIGHLIGHT_CHARS;
    if (langId !== "plain" && !tooLarge) {
      try {
        prism = await this.plugin.getPrism();
      } catch (e) {
        console.warn("Code File Viewer: loadPrism() failed", e);
      }
      if (seq !== this.renderSeq) return;
      grammar = (_g = (_e = prism == null ? void 0 : prism.languages) == null ? void 0 : _e[langId]) != null ? _g : (_f = prism == null ? void 0 : prism.languages) == null ? void 0 : _f[ext];
    }
    if (prism && grammar) {
      const tokens = prism.tokenize(this.data, grammar);
      appendTokenStream(code, tokens);
    } else {
      code.setText(this.data);
      if (langId !== "plain") {
        note.setText(
          tooLarge ? "highlighting off (large file)" : `no grammar for "${langId}" \u2014 plain text`
        );
      }
    }
  }
};
function appendTokenStream(parent, stream) {
  if (typeof stream === "string") {
    parent.appendText(stream);
    return;
  }
  if (Array.isArray(stream)) {
    for (const part of stream) appendTokenStream(parent, part);
    return;
  }
  const classes = ["token", stream.type];
  const alias = stream.alias;
  if (alias) {
    if (Array.isArray(alias)) classes.push(...alias);
    else classes.push(alias);
  }
  const span = parent.createSpan({ cls: classes });
  appendTokenStream(span, stream.content);
}
function parseMappings(text) {
  const map = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const match = line.match(/^\.?([\w+-]+)\s*[:=]\s*([\w+-]+)$/);
    if (match) map[match[1].toLowerCase()] = match[2].toLowerCase();
  }
  return map;
}
function formatMappings(map) {
  return Object.keys(map).sort().map((ext) => `${ext}: ${map[ext]}`).join("\n");
}
var CodeFileViewerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Line numbers").setDesc("Show a line-number gutter next to the code.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.lineNumbers).onChange(async (value) => {
        this.plugin.settings.lineNumbers = value;
        await this.plugin.saveSettings();
        this.plugin.rerenderOpenViews();
      })
    );
    const applyMappings = (0, import_obsidian.debounce)(
      async (value) => {
        this.plugin.settings.extensionMap = parseMappings(value);
        await this.plugin.saveSettings();
        this.plugin.applyExtensions();
        this.plugin.rerenderOpenViews();
      },
      800,
      true
    );
    new import_obsidian.Setting(containerEl).setName("Extension \u2192 language mappings").setDesc(
      'One mapping per line, in the form "extension: language". Language ids are the same ones you use in ```lang code blocks. Use "plain" to open a file type without highlighting. Lines starting with # are ignored. If removing an extension doesn\'t take effect, toggle the plugin off and on.'
    ).addTextArea((ta) => {
      ta.setValue(formatMappings(this.plugin.settings.extensionMap));
      ta.onChange(applyMappings);
      ta.inputEl.rows = 14;
      ta.inputEl.addClass("cfv-settings-textarea");
    });
    new import_obsidian.Setting(containerEl).setName("Restore default mappings").setDesc("Replace the list above with the plugin's built-in defaults.").addButton(
      (btn) => btn.setButtonText("Restore defaults").onClick(async () => {
        this.plugin.settings.extensionMap = { ...DEFAULT_EXTENSION_MAP };
        await this.plugin.saveSettings();
        this.plugin.applyExtensions();
        this.plugin.rerenderOpenViews();
        this.display();
      })
    );
  }
};
